apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service-deployment
  namespace: helios
  labels:
    app: helios
    component: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helios
      component: analytics-service
  template:
    metadata:
      labels:
        app: helios
        component: analytics-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: analytics-service
          image: ghcr.io/jigarbhoye04/helios/analytics-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secrets
                  key: databaseUrl
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secrets
  namespace: helios
  labels:
    app: helios
    component: analytics-service
stringData:
  databaseUrl: postgresql://helios:change-me@postgres.helios.svc.cluster.local:5432/helios
