apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: helios
  labels:
    app: helios
    component: analytics-service
spec:
  selector:
    app: helios
    component: analytics-service
    role: api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
