apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-request-handler-deployment
  namespace: helios
  labels:
    app: helios
    component: bid-request-handler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helios
      component: bid-request-handler
  template:
    metadata:
      labels:
        app: helios
        component: bid-request-handler
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2112"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: bid-request-handler
          image: helios/bid-request-handler:phase4
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 2112
              name: metrics
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: helios-kafka-config
                  key: KAFKA_BROKERS
            - name: KAFKA_TOPIC_BID_REQUESTS
              valueFrom:
                configMapKeyRef:
                  name: helios-kafka-config
                  key: KAFKA_TOPIC_BID_REQUESTS
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
