apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: helios
  labels:
    app: helios
    component: postgres
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: helios
      component: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: helios
        component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: helios
  labels:
    app: helios
    component: postgres
spec:
  type: ClusterIP
  selector:
    app: helios
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
  namespace: helios
  labels:
    app: helios
    component: postgres
stringData:
  database: helios
  username: helios
  password: jigxPostgres
