# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_profile.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'user_profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_profile.proto\x12\x12helios.userprofile\"(\n\x15GetUserProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"+\n\x08Interest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\"\xdd\x01\n\x0bUserProfile\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06locale\x18\x02 \x01(\t\x12/\n\tinterests\x18\x03 \x03(\x0b\x32\x1c.helios.userprofile.Interest\x12G\n\x0c\x64\x65mographics\x18\x04 \x03(\x0b\x32\x31.helios.userprofile.UserProfile.DemographicsEntry\x1a\x33\n\x11\x44\x65mographicsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"J\n\x16GetUserProfileResponse\x12\x30\n\x07profile\x18\x01 \x01(\x0b\x32\x1f.helios.userprofile.UserProfile2}\n\x12UserProfileService\x12g\n\x0eGetUserProfile\x12).helios.userprofile.GetUserProfileRequest\x1a*.helios.userprofile.GetUserProfileResponseB>Z<github.com/your-username/helios-rtb-engine/proto/userprofileb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/your-username/helios-rtb-engine/proto/userprofile'
  _globals['_USERPROFILE_DEMOGRAPHICSENTRY']._loaded_options = None
  _globals['_USERPROFILE_DEMOGRAPHICSENTRY']._serialized_options = b'8\001'
  _globals['_GETUSERPROFILEREQUEST']._serialized_start=42
  _globals['_GETUSERPROFILEREQUEST']._serialized_end=82
  _globals['_INTEREST']._serialized_start=84
  _globals['_INTEREST']._serialized_end=127
  _globals['_USERPROFILE']._serialized_start=130
  _globals['_USERPROFILE']._serialized_end=351
  _globals['_USERPROFILE_DEMOGRAPHICSENTRY']._serialized_start=300
  _globals['_USERPROFILE_DEMOGRAPHICSENTRY']._serialized_end=351
  _globals['_GETUSERPROFILERESPONSE']._serialized_start=353
  _globals['_GETUSERPROFILERESPONSE']._serialized_end=427
  _globals['_USERPROFILESERVICE']._serialized_start=429
  _globals['_USERPROFILESERVICE']._serialized_end=554
# @@protoc_insertion_point(module_scope)
