# Generated by Django 5.2.7 on 2025-10-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_id', models.CharField(db_index=True, help_text='Unique identifier for the bid request', max_length=255)),
                ('user_id', models.CharField(db_index=True, help_text='User identifier associated with the bid', max_length=255)),
                ('site_domain', models.CharField(blank=True, db_index=True, help_text='Domain of the site where the ad would be displayed', max_length=255, null=True)),
                ('win_status', models.BooleanField(db_index=True, default=False, help_text='Whether the bid won the auction')),
                ('win_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Final price paid for the auction win (in USD)', max_digits=10)),
                ('bid_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Original bid price submitted', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('enriched', models.BooleanField(default=False, help_text='Whether the bid was enriched with user profile data')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the outcome was recorded')),
                ('auction_timestamp', models.DateTimeField(blank=True, help_text='Timestamp when the auction was processed', null=True)),
                ('user_interests', models.JSONField(blank=True, default=list, help_text='User interests from profile enrichment')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Raw auction outcome data from Kafka')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in the database')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
            ],
            options={
                'verbose_name': 'Auction Outcome',
                'verbose_name_plural': 'Auction Outcomes',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='outcomes_au_timesta_bfa7be_idx'), models.Index(fields=['win_status', '-timestamp'], name='outcomes_au_win_sta_cfc5a5_idx'), models.Index(fields=['user_id', '-timestamp'], name='outcomes_au_user_id_7f191c_idx'), models.Index(fields=['site_domain', '-timestamp'], name='outcomes_au_site_do_528f8a_idx')],
            },
        ),
    ]
