apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: helios
  labels:
    app: helios
    component: kafka
spec:
  serviceName: kafka
  selector:
    matchLabels:
      app: helios
      component: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: helios
        component: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                secretKeyRef:
                  name: kafka-config
                  key: zookeeperConnect
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-service.helios.svc.cluster.local:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: helios
  labels:
    app: helios
    component: kafka
spec:
  clusterIP: None
  selector:
    app: helios
    component: kafka
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: helios
  labels:
    app: helios
    component: kafka
spec:
  selector:
    app: helios
    component: kafka
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-config
  namespace: helios
  labels:
    app: helios
    component: kafka
stringData:
  zookeeperConnect: zookeeper.helios.svc.cluster.local:2181
