apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: helios
  labels:
    app: helios
    component: kafka
spec:
  serviceName: kafka
  selector:
    matchLabels:
      app: helios
      component: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: helios
        component: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.7.0
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              valueFrom:
                secretKeyRef:
                  name: kafka-config
                  key: zookeeperConnect
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka.helios.svc.cluster.local:9092
          volumeMounts:
            - name: data
              mountPath: /bitnami/kafka
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: helios
  labels:
    app: helios
    component: kafka
spec:
  clusterIP: None
  selector:
    app: helios
    component: kafka
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-config
  namespace: helios
  labels:
    app: helios
    component: kafka
stringData:
  zookeeperConnect: zookeeper.helios.svc.cluster.local:2181
