apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: helios
  labels:
    app: helios
    component: zookeeper
spec:
  serviceName: zookeeper
  selector:
    matchLabels:
      app: helios
      component: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: helios
        component: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.5.1
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "2"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "5"
          ports:
            - containerPort: 2181
          volumeMounts:
            - name: data
              mountPath: /var/lib/zookeeper
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: helios
  labels:
    app: helios
    component: zookeeper
spec:
  clusterIP: None
  selector:
    app: helios
    component: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: 2181
