apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidding-logic-service-deployment
  namespace: helios
  labels:
    app: helios
    component: bidding-logic-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helios
      component: bidding-logic-service
  template:
    metadata:
      labels:
        app: helios
        component: bidding-logic-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: bidding-logic-service
          image: helios/bidding-logic-service:phase4
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
              name: metrics
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: helios-kafka-config
                  key: KAFKA_BROKERS
            - name: KAFKA_TOPIC_BID_REQUESTS
              valueFrom:
                configMapKeyRef:
                  name: helios-kafka-config
                  key: KAFKA_TOPIC_BID_REQUESTS
            - name: KAFKA_CONSUMER_GROUP
              valueFrom:
                configMapKeyRef:
                  name: helios-kafka-config
                  key: KAFKA_CONSUMER_GROUP
            - name: KAFKA_TOPIC_BID_RESPONSES
              value: bid_responses
            - name: USER_PROFILE_SVC_ADDR
              value: user-profile-service.helios.svc.cluster.local:50051
            - name: USER_PROFILE_SVC_TIMEOUT
              value: "2.0"
            - name: METRICS_PORT
              value: "8001"
