apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidding-logic-service-deployment
  namespace: helios
  labels:
    app: helios
    component: bidding-logic-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helios
      component: bidding-logic-service
  template:
    metadata:
      labels:
        app: helios
        component: bidding-logic-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: bidding-logic-service
          image: helios/bidding-logic-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
              name: metrics
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: helios-kafka-config
                  key: KAFKA_BROKERS
            - name: KAFKA_TOPIC_BID_REQUESTS
              valueFrom:
                configMapKeyRef:
                  name: helios-kafka-config
                  key: KAFKA_TOPIC_BID_REQUESTS
            - name: KAFKA_CONSUMER_GROUP
              valueFrom:
                configMapKeyRef:
                  name: helios-kafka-config
                  key: KAFKA_CONSUMER_GROUP
            - name: KAFKA_TOPIC_BID_RESPONSES
              value: bid_responses
            - name: USER_PROFILE_SVC_ADDR
              value: user-profile-service.helios.svc.cluster.local:50051
            - name: USER_PROFILE_SVC_TIMEOUT
              value: "2.0"
            - name: METRICS_PORT
              value: "8001"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
