apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidding-logic-service-deployment
  namespace: helios
  labels:
    app: helios
    component: bidding-logic-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helios
      component: bidding-logic-service
  template:
    metadata:
      labels:
        app: helios
        component: bidding-logic-service
    spec:
      containers:
        - name: bidding-logic-service
          image: helios/bidding-logic-service:phase2
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: helios-kafka-config
                  key: KAFKA_BROKERS
            - name: KAFKA_TOPIC_BID_REQUESTS
              valueFrom:
                configMapKeyRef:
                  name: helios-kafka-config
                  key: KAFKA_TOPIC_BID_REQUESTS
            - name: KAFKA_CONSUMER_GROUP
              valueFrom:
                configMapKeyRef:
                  name: helios-kafka-config
                  key: KAFKA_CONSUMER_GROUP
